name: Deploy to Bothost

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Bothost
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.BOTHOST_HOST }}
        username: ${{ secrets.BOTHOST_USERNAME }}
        key: ${{ secrets.BOTHOST_SSH_KEY }}
        script: |
          cd ${{ secrets.BOT_DIRECTORY }}
          
          # Останавливаем текущего бота
          pkill -f "python.*bot" || true
          sleep 2
          
          # Обновляем код
          git pull origin main
          
          # Создаем виртуальное окружение если нужно
          if [ ! -d "venv" ]; then
            python -m venv venv
          fi
          source venv/bin/activate
          
          # Устанавливаем зависимости
          pip install -r requirements.txt
          
          # Создаем файл с service account
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          
          # Запускаем бота в фоне
          nohup python -u your_main_bot_file.py > bot.log 2>&1 &
          echo "Bot deployed successfully!"
          
          # Ждем немного и проверяем что бот запустился
          sleep 5
          pgrep -f "python.*bot" && echo "Bot is running!" || echo "Bot failed to start!"
